name: news_app2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2+7

environment:
  sdk: '3.8.1'

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.3.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.4.9
  freezed: ^3.1.0
  freezed_annotation: ^3.1.0
  loading_animation_widget: ^1.2.0+4
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.3
  webview_flutter: ^4.8.0
  win32: ^5.1.4

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - flutter.env
