Map<String, Map<String, dynamic>> countriesMap = {
  'ae': {
    'name': 'United Arab Emirates',
    'id': 784,
    'flag': '🇦🇪',
    'code': 'ae',
  },
  'ar': {
    'name': 'Argentina',
    'id': 32,
    'flag': '🇦🇷',
    'code': 'ar',
  },
  'at': {
    'name': 'Austria',
    'id': 40,
    'flag': '🇦🇹',
    'code': 'at',
  },
  'au': {
    'name': 'Australia',
    'id': 36,
    'flag': '🇦🇺',
    'code': 'au',
  },
  'be': {
    'name': 'Belgium',
    'id': 56,
    'flag': '🇧🇪',
    'code': 'be',
  },
  'bg': {
    'name': 'Bulgaria',
    'id': 100,
    'flag': '🇧🇬',
    'code': 'bg',
  },
  'br': {
    'name': 'Brazil',
    'id': 76,
    'flag': '🇧🇷',
    'code': 'br',
  },
  'ca': {
    'name': 'Canada',
    'id': 124,
    'flag': '🇨🇦',
    'code': 'ca',
  },
  'ch': {
    'name': 'Switzerland',
    'id': 756,
    'flag': '🇨🇭',
    'code': 'ch',
  },
  'cn': {
    'name': 'China',
    'id': 156,
    'flag': '🇨🇳',
    'code': 'cn',
  },
  'co': {
    'name': 'Colombia',
    'id': 170,
    'flag': '🇨🇴',
    'code': 'co',
  },
  'cu': {
    'name': 'Cuba',
    'id': 192,
    'flag': '🇨🇺',
    'code': 'cu',
  },
  'cz': {
    'name': 'Czech Republic',
    'id': 203,
    'flag': '🇨🇿',
    'code': 'cz',
  },
  'de': {
    'name': 'Germany',
    'id': 276,
    'flag': '🇩🇪',
    'code': 'de',
  },
  'eg': {
    'name': 'Egypt',
    'id': 818,
    'flag': '🇪🇬',
    'code': 'eg',
  },
  'fr': {
    'name': 'France',
    'id': 250,
    'flag': '🇫🇷',
    'code': 'fr',
  },
  'gb': {
    'name': 'United Kingdom',
    'id': 826,
    'flag': '🇬🇧',
    'code': 'gb',
  },
  'gr': {
    'name': 'Greece',
    'id': 300,
    'flag': '🇬🇷',
    'code': 'gr',
  },
  'hk': {
    'name': 'Hong Kong',
    'id': 344,
    'flag': '🇭🇰',
    'code': 'hk',
  },
  'hu': {
    'name': 'Hungary',
    'id': 348,
    'flag': '🇭🇺',
    'code': 'hu',
  },
  'id': {
    'name': 'Indonesia',
    'id': 360,
    'flag': '🇮🇩',
    'code': 'id',
  },
  'ie': {
    'name': 'Ireland',
    'id': 372,
    'flag': '🇮🇪',
    'code': 'ie',
  },
  'il': {
    'name': 'Israel',
    'id': 376,
    'flag': '🇮🇱',
    'code': 'il',
  },
  'in': {
    'name': 'India',
    'id': 356,
    'flag': '🇮🇳',
    'code': 'in',
  },
  'it': {
    'name': 'Italy',
    'id': 380,
    'flag': '🇮🇹',
    'code': 'it',
  },
  'jp': {
    'name': 'Japan',
    'id': 392,
    'flag': '🇯🇵',
    'code': 'jp',
  },
  'kr': {
    'name': 'South Korea',
    'id': 410,
    'flag': '🇰🇷',
    'code': 'kr',
  },
  'lt': {
    'name': 'Lithuania',
    'id': 440,
    'flag': '🇱🇹',
    'code': 'lt',
  },
  'lv': {
    'name': 'Latvia',
    'id': 428,
    'flag': '🇱🇻',
    'code': 'lv',
  },
  'ma': {
    'name': 'Morocco',
    'id': 504,
    'flag': '🇲🇦',
    'code': 'ma',
  },
  'mx': {
    'name': 'Mexico',
    'id': 484,
    'flag': '🇲🇽',
    'code': 'mx',
  },
  'my': {
    'name': 'Malaysia',
    'id': 458,
    'flag': '🇲🇾',
    'code': 'my',
  },
  'ng': {
    'name': 'Nigeria',
    'id': 566,
    'flag': '🇳🇬',
    'code': 'ng',
  },
  'nl': {
    'name': 'Netherlands',
    'id': 528,
    'flag': '🇳🇱',
    'code': 'nl',
  },
  'no': {
    'name': 'Norway',
    'id': 578,
    'flag': '🇳🇴',
    'code': 'no',
  },
  'nz': {
    'name': 'New Zealand',
    'id': 554,
    'flag': '🇳🇿',
    'code': 'nz',
  },
  'ph': {
    'name': 'Philippines',
    'id': 608,
    'flag': '🇵🇭',
    'code': 'ph',
  },
  'pl': {
    'name': 'Poland',
    'id': 616,
    'flag': '🇵🇱',
    'code': 'pl',
  },
  'pt': {
    'name': 'Portugal',
    'id': 620,
    'flag': '🇵🇹',
    'code': 'pt',
  },
  'ro': {
    'name': 'Romania',
    'id': 642,
    'flag': '🇷🇴',
    'code': 'ro',
  },
  'rs': {
    'name': 'Serbia',
    'id': 688,
    'flag': '🇷🇸',
    'code': 'rs',
  },
  'ru': {
    'name': 'Russia',
    'id': 643,
    'flag': '🇷🇺',
    'code': 'ru',
  },
  'sa': {
    'name': 'Saudi Arabia',
    'id': 682,
    'flag': '🇸🇦',
    'code': 'sa',
  },
  'se': {
    'name': 'Sweden',
    'id': 752,
    'flag': '🇸🇪',
    'code': 'se',
  },
  'sg': {
    'name': 'Singapore',
    'id': 702,
    'flag': '🇸🇬',
    'code': 'sg',
  },
  'si': {
    'name': 'Slovenia',
    'id': 705,
    'flag': '🇸🇮',
    'code': 'si',
  },
  'sk': {
    'name': 'Slovakia',
    'id': 703,
    'flag': '🇸🇰',
    'code': 'sk',
  },
  'th': {
    'name': 'Thailand',
    'id': 764,
    'flag': '🇹🇭',
    'code': 'th',
  },
  'tr': {
    'name': 'Turkey',
    'id': 792,
    'flag': '🇹🇷',
    'code': 'tr',
  },
  'tw': {
    'name': 'Taiwan',
    'id': 158,
    'flag': '🇹🇼',
    'code': 'tw',
  },
  'ua': {
    'name': 'Ukraine',
    'id': 804,
    'flag': '🇺🇦',
    'code': 'ua',
  },
  'us': {
    'name': 'United States',
    'id': 840,
    'flag': '🇺🇸',
    'code': 'us',
  },
  've': {
    'name': 'Venezuela',
    'id': 862,
    'flag': '🇻🇪',
    'code': 've',
  },
  'za': {
    'name': 'South Africa',
    'id': 710,
    'flag': '🇿🇦',
    'code': 'za',
  },
};
